openapi: 3.0.0
info:
  title: Sample API
  description: API for demonstrating Swagger Viewer in VS Code
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
